$(document).ready(function(){
	function validate() {
		$("#formulario").validate({
			rules:{
				nombre:{
					required:true
				},
				firstName:{
					required:true
				},
				lastName:{
					required:true
				},
				nombreGenerico:{
					required:true
				},
				nombreComercial:{
					required:true
				},
				presentacion:{
					required:true
				},
				grupoMedicamento:{
                	required:true
				},
				sitio:{
					required:true,
					url:true
				},
				email:{
					required:true,
					email:true
				},
				password:{
					required:true,
					minlength:6
				},
				confirmPassword:{
					required:true,
					equalTo:"#password"
				},
				clave:{
					required:true,
					minlength:6
				},
				clave2:{
					required:true,
					equalTo:"#clave"
				},
				cancel:{
					
				},
				phoneNumber:{
					digits:true
				},
				matricula:{
					required:true,
					digits:true
				},
				calle:{
					required:true
				},
				numero:{
					required:true,
					digits:true
				},
				dni:{
					required:true,
					number:true,
					minlength:7,
					maxlength:8
				},
				sexo:{
					required:true
				},
				fch_nac:{
					required:true
				},
				fechaTratamiento:{
				    required:true
				},
				fechaAlta:{
					required:true
				},
				fechaHasta:{
					required:true
				},
                dia:{
                    required:true
                },
				mes:{
					required:true,
                    digits:true,
                    maxlength:2
				},
				anio:{
					required:true,
					digits:true,
					maxlength:4
				},
				medicion:{
				    required:true,
				    digits:true
				},
				provincia:{
					required:true
				},
				localidad:{
				},
				limiteInferior:{
					digits:true
				},
				limiteSuperior:{
					digits:true
				},
                cantidadLunes1:{
                	required:true
                },
                observacionesLunes1:{
                	required:true
                },
                cantidadMartes1:{
                required:true
                },
                observacionesMartes1:{
                required:true
                },
                cantidadMiercoles1:{
                required:true
                },
                observacionesMiercoles1:{
                required:true
                },
                cantidadJueves1:{
                required:true
                },
                observacionesJueves1:{
                required:true
                },
                cantidadViernes1:{
                required:true
                },
                observacionesViernes1:{
                required:true
                },
                cantidadSabado1:{
                required:true
                },
                observacionesSabado1:{
                required:true
                },
                cantidadAlimentoLunes2:{
                required:true
                },
                observacionAlimentoLunes2:{
                required:true
                },
                cantidadAlimentoLunes3:{
                required:true
                },
                observacionAlimentoLunes3:{
                required:true
                },
                cantidadAlimentoLunes4:{
                required:true
                },
                observacionAlimentoLunes4:{
                required:true
                },
                cantidadAlimentoLunes5:{
                required:true
                },
                observacionAlimentoLunes5:{
                required:true
                },
                cantidadAlimentoLunes6:{
                required:true
                },
                observacionAlimentoLunes6:{
                required:true
                },
                cantidadAlimentoLunes7:{
                required:true
                },
                observacionAlimentoLunes7:{
                required:true
                },
                cantidadAlimentoLunes8:{
                required:true
                },
                observacionAlimentoLunes8:{
                required:true
                },
               	cantidadAlimentoLunes9:{
                required:true
                },
                observacionAlimentoLunes9:{
                required:true
                },
                cantidadAlimentoLunes10:{
                required:true
                },
                observacionAlimentoLunes10:{
                required:true
                },
                cantidadAlimentoMartes11:{
                required:true
                },
                observacionAlimentoMartes11:{
                required:true
                },
                cantidadAlimentoMartes12:{
                required:true
                },
                observacionAlimentoMartes12:{
                required:true
                },
                cantidadAlimentoMartes13:{
                required:true
                },
                observacionAlimentoMartes13:{
                required:true
                },
                cantidadAlimentoMartes14:{
                required:true
                },
                observacionAlimentoMartes14:{
                required:true
                },
                cantidadAlimentoMartes15:{
                required:true
                },
                observacionAlimentoMartes15:{
                required:true
                },
                cantidadAlimentoMartes16:{
                required:true
                },
                observacionAlimentoMartes16:{
                required:true
                },
                cantidadAlimentoMartes17:{
                required:true
                },
                observacionAlimentoMartes17:{
                required:true
                },
                cantidadAlimentoMartes18:{
                required:true
                },
                observacionAlimentoMartes18:{
                required:true
                },
                cantidadAlimentoMartes19:{
                required:true
                },
                observacionAlimentoMartes19:{
                required:true
                },
                cantidadAlimentoMartes20:{
                required:true
                },
                observacionAlimentoMartes20:{
                required:true
                },
                cantidadAlimentoMiercoles21:{
                required:true
                },
                observacionAlimentoMiercoles21:{
                required:true
                },
                cantidadAlimentoMiercoles22:{
                required:true
                },
                observacionAlimentoMiercoles22:{
                required:true
                },
                cantidadAlimentoMiercoles23:{
                required:true
                },
                observacionAlimentoMiercoles23:{
                required:true
                },
                cantidadAlimentoMiercoles24:{
                required:true
                },
                observacionAlimentoMiercoles24:{
                required:true
                },
                cantidadAlimentoMiercoles25:{
                required:true
                },
                observacionAlimentoMiercoles25:{
                required:true
                },
                cantidadAlimentoMiercoles26:{
                required:true
                },
                observacionAlimentoMiercoles26:{
                required:true
                },
                cantidadAlimentoMiercoles27:{
                required:true
                },
                observacionAlimentoMiercoles27:{
                required:true
                },
                cantidadAlimentoMiercoles28:{
                required:true
                },
                observacionAlimentoMiercoles28:{
                required:true
                },
                cantidadAlimentoMiercoles29:{
                required:true
                },
                observacionAlimentoMiercoles29:{
                required:true
                },
                cantidadAlimentoMiercoles20:{
                required:true
                },
                observacionAlimentoMiercoles20:{
                required:true
                },
                cantidadAlimentoJueves31:{
                required:true
                },
                observacionAlimentoJueves31:{
                required:true
                },
                cantidadAlimentoJueves32:{
                required:true
                },
                observacionAlimentoJueves32:{
                required:true
                },
                cantidadAlimentoJueves33:{
                required:true
                },
                observacionAlimentoJueves33:{
                required:true
                },
                cantidadAlimentoJueves34:{
                required:true
                },
                observacionAlimentoJueves34:{
                required:true
                },
                cantidadAlimentoJueves35:{
                required:true
                },
                observacionAlimentoJueves35:{
                required:true
                },
                cantidadAlimentoJueves36:{
                required:true
                },
                observacionAlimentoJueves36:{
                required:true
                },
                cantidadAlimentoJueves37:{
                required:true
                },
                observacionAlimentoJueves37:{
                required:true
                },
                cantidadAlimentoJueves38:{
                required:true
                },
                observacionAlimentoJueves38:{
                required:true
                },
                cantidadAlimentoJueves39:{
                required:true
                },
                observacionAlimentoJueves39:{
                required:true
                },
                cantidadAlimentoJueves40:{
                required:true
                },
                observacionAlimentoJueves40:{
                required:true
                },
				cantidadAlimentoViernes41:{
                required:true
                },
                observacionAlimentoViernes41:{
                required:true
                },
                cantidadAlimentoViernes42:{
                required:true
                },
                observacionAlimentoViernes42:{
                required:true
                },
                cantidadAlimentoViernes43:{
                required:true
                },
                observacionAlimentoViernes43:{
                required:true
                },
                cantidadAlimentoViernes44:{
                required:true
                },
                observacionAlimentoViernes44:{
                required:true
                },
                cantidadAlimentoViernes45:{
                required:true
                },
                observacionAlimentoViernes45:{
                required:true
                },
                cantidadAlimentoViernes46:{
                required:true
                },
                observacionAlimentoViernes46:{
                required:true
                },
                cantidadAlimentoViernes47:{
                required:true
                },
                observacionAlimentoViernes47:{
                required:true
                },
                cantidadAlimentoViernes48:{
                required:true
                },
                observacionAlimentoViernes48:{
                required:true
                },
                cantidadAlimentoViernes49:{
                required:true
                },
                observacionAlimentoViernes49:{
                required:true
                },
                cantidadAlimentoViernes50:{
                required:true
                },
                observacionAlimentoViernes50:{
                required:true
                },
				cantidadAlimentoSabado51:{
                required:true
                },
                observacionAlimentoSabado51:{
                required:true
                },
                cantidadAlimentoSabado52:{
                required:true
                },
                observacionAlimentoSabado52:{
                required:true
                },
                cantidadAlimentoSabado53:{
                required:true
                },
                observacionAlimentoSabado53:{
                required:true
                },
                cantidadAlimentoSabado54:{
                required:true
                },
                observacionAlimentoSabado54:{
                required:true
                },
                cantidadAlimentoSabado55:{
                required:true
                },
                observacionAlimentoSabado55:{
                required:true
                },
                cantidadAlimentoSabado56:{
                required:true
                },
                observacionAlimentoSabado56:{
                required:true
                },
                cantidadAlimentoSabado57:{
                required:true
                },
                observacionAlimentoSabado57:{
                required:true
                },
                cantidadAlimentoSabado58:{
                required:true
                },
                observacionAlimentoSabado58:{
                required:true
                },
                cantidadAlimentoSabado59:{
                required:true
                },
                observacionAlimentoSabado59:{
                required:true
                },
                cantidadAlimentoSabado60:{
                required:true
                },
                observacionAlimentoSabado60:{
                required:true
                }
			},
			success:function(etiqueta){
				console.log(etiqueta);
				$(etiqueta).addClass("valid");
			}
		});
	}

	validate();

	$("#formulario input").blur(function() {
		validate();
	});

	$("#formulario input").focusout(function()
	{
		if ( !$(this).val() ) {
			$(this).parent().find(".error").text("Error! El campo se encuentra vacio");
		}
	});
	
});